### ISSUE TITLE
[Pair Programming] Create new branch in the Kuadra project

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadra#27]
**WHAT**
Create a new github branch that will be the base branch for https://github.com/Kuadrant/kuadra/issues/29 https://github.com/Kuadrant/kuadra/issues/30

**Comment by ehearneRedHat** [comment]
Branch `temp_base` has been [created](https://github.com/Kuadrant/kuadra/tree/temp_base) on the origin `kuadra`. @ehearneRedHat lead the pair programming and @dlaw4608 observed.
