### ISSUE TITLE
[SPIKE] Investigate which k8s tool and version to use for Kuadra

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadra#28]
WHAT:
OperatorSDK and kube builder are the 2 major k8s controller building tools. 
* See if there's any new tools we could use
* Have a look at which one is best and come up with pros and cons of each. 
* What version should we go with?

**Comment by ehearneRedHat** [comment]
Myself and @dlaw4608 agreed to use operator-sdk due to its simplicity and streamlined experience for beginners, quickstart, growing ecosystem and compliance with the Operator Lifecycle Management. Also, custom controller support and Ansible if desired in the future.

**Comment by R-Lawton** [comment]
Deadly sounds great
