### ISSUE TITLE
[Pair Programming] Create the skeleton or scaffolding using the chosen tool

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadra#29]
**WHAT:**
Using the tool chosen from the spike create the scaffolding for the project

**HOW:**
In the new branch that was created use the tool to create the scaffolding or skeleton that the project will build on

**WHY:**
This is the perfect opportunity to see what gets created where and why as well as see what comes by default with the tool

**Comment by KevFan** [comment]
This issue is a good pair programming candidate

**Comment by ehearneRedHat** [comment]
We (@ehearneRedHat and @dlaw4608) chose to use operator-sdk, as mentioned in #28 .

**Comment by ehearneRedHat** [comment]
#33 has been reviewed and approved. Awaiting merge to close...

**Comment by ehearneRedHat** [comment]
Reopening issue as operator was not generated successfully...

**Comment by ehearneRedHat** [comment]
Issue resolved in #30 . Closing...
