### ISSUE TITLE
Code migration from the old branch to the new branch

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadra#30]
**WHAT**
Once https://github.com/Kuadrant/kuadra/issues/29 is complete, migrate the current feature set / code to the new branch

**Comment by ehearneRedHat** [comment]
We are using [this documentation](https://sdk.operatorframework.io/docs/building-operators/golang/migration/) to migrate the code.

**Comment by ehearneRedHat** [comment]
Still in progress... will continue on Thursday, both myself and @dlaw4608 .

**Comment by ehearneRedHat** [comment]
Continued with issue, generating the operator skeleton was not completed successfully. Re-opening #29 ...

**Comment by ehearneRedHat** [comment]
Issue has been resolved in #34 . Closing now...
